---
title: "amenity_mix"
output: html_document
date: "2023-04-05"
---

```{r}
library(librarian)
shelf(googleway, tidyverse, tmap, sf)

api <- "AIzaSyAZV49JhrDtgmPIWhw0pUvlVKBJ9Gr_k6I"
```

```{r}
suburb1 <- c('Abbotsbury', 'Abbotsford', 'Acacia Gardens', 'Agnes Banks', 'Airds', 'Alexandria', 'Alfords Point', 'Alison', 'Allambie', 'Allambie Heights', 'Allawah', 'Ambarvale', 'Annandale', 'Annangrove', 'Appin', 'Arcadia', 'Arncliffe', 'Arndell Park', 'Artarmon', 'Ashbury', 'Ashcroft', 'Ashfield', 'Asquith', 'Auburn', 'Austral', 'Avalon', 'Avalon Beach', 'Avoca Beach', 'Badgerys Creek', 'Balgowlah', 'Balgowlah Heights', 'Balmain', 'Balmain East', 'Bangor', 'Banksia', 'Banksmeadow', 'Bankstown', 'Bar Point', 'Barangaroo', 'Barden Ridge', 'Bardia', 'Bardwell Park', 'Bardwell Valley', 'Bargo', 'Bass Hill', 'Bateau Bay', 'Baulkham Hills', 'Bayview', 'Beacon Hill', 'Beaconsfield', 'Beaumont Hills', 'Beecroft', 'Belfield', 'Belimbla Park', 'Bell', 'Bella Vista', 'Bella Vista Waters', 'Bellevue Hill', 'Belmore', 'Belrose', 'Bensville', 'Berala', 'Berambing', 'Berkeley Vale', 'Berkshire Park', 'Berowra', 'Berowra Creek', 'Berowra Heights', 'Berowra Waters', 'Berrilee', 'Beverley Park', 'Beverly Hills', 'Bexley', 'Bexley North', 'Bidwill', 'Bilgola', 'Bilgola Beach', 'Bilgola Plateau', 'Bilpin', 'Birchgrove', 'Birrong', 'Blackett', 'Blackheath', 'Blacktown', 'Blacktown Westpoint', 'Blackwall', 'Blair Athol', 'Blairmount', 'Blakehurst', 'Blaxland', 'Blaxlands Ridge', 'Bligh Park', 'Blue Bay', 'Blue Haven', 'Blue Mountains National P…', 'Bondi', 'Bondi Beach', 'Bondi Junction', 'Bondi Junction Plaza', 'Bonnet Bay', 'Bonnyrigg', 'Bonnyrigg Heights', 'Booker Bay', 'Boronia Park', 'Bossley Park', 'Botany', 'Bow Bowing', 'Bowen Mountain', 'Box Hill', 'Bradbury', 'Breakfast Point', 'Brighton-le-sands', 'Bringelly', 'Bronte', 'Brooklyn', 'Brookvale', 'Brownlow Hill', 'Bucketty', 'Budgewoi', 'Buff Point', 'Bullaburra', 'Bundeena', 'Bungarribee', 'Burraneer', 'Burwood', 'Burwood Heights', 'Busby', 'Buxton', 'Cabarita', 'Cabramatta', 'Cabramatta West', 'Caddens', 'Calga', 'Cambridge Gardens', 'Cambridge Park', 'Camden', 'Camden Park', 'Camden South', 'Camellia', 'Cammeray', 'Campbelltown', 'Camperdown', 'Campsie', 'Canada Bay', 'Canley Heights', 'Canley Vale', 'Canoelands', 'Canterbury', 'Canton Beach', 'Caringbah', 'Caringbah South', 'Carlingford', 'Carlton', 'Carnes Hill', 'Carramar', 'Carss Park', 'Cartwright', 'Castle Cove', 'Castle Hill', 'Castlecrag', 'Castlereagh', 'Casula', 'Catherine Field', 'Cattai', 'Cawdor', 'Cecil Hills', 'Cecil Park', 'Cedar Brush Creek', 'Centennial Park', 'Central Mangrove', 'Chain Valley Bay', 'Charmhaven', 'Chatswood', 'Chatswood West', 'Cheltenham', 'Cherrybrook', 'Chester Hill', 'Chifley', 'Chippendale', 'Chipping Norton', 'Chiswick', 'Chittaway Bay', 'Chittaway Point', 'Chullora', 'Church Point', 'Claremont Meadows', 'Clareville', 'Claymore', 'Clemton Park', 'Clontarf', 'Clovelly', 'Clyde', 'Coasters Retreat', 'Cobbitty', 'Cogra Bay', 'Colebee', 'Collaroy', 'Collaroy Beach', 'Collaroy Plateau', 'Colo', 'Colo Heights', 'Colongra', 'Colyton', 'Como', 'Concord', 'Concord West', 'Condell Park', 'Connells Point', 'Constitution Hill', 'Coogee', 'Copacabana', 'Cornwallis', 'Cottage Point', 'Couridjah', 'Cowan', 'Cranebrook', 'Crangan Bay', 'Cremorne', 'Cremorne Point', 'Cromer', 'Cronulla', 'Crows Nest', 'Croydon', 'Croydon Park', 'Cumberland Reach', 'Curl Curl', 'Currans Hill', 'Daceyville', 'Daleys Point', 'Dangar Island', 'Darling Island', 'Darling Point', 'Darlinghurst', 'Darlington', 'Davidson', 'Davistown', 'Dawes Point', 'Dean Park', 'Dee Why', 'Dee Why Beach', 'Denham Court', 'Denistone', 'Denistone East', 'Denistone West', 'Dharruk', 'Dolans Bay', 'Dolls Point', 'Doonside', 'Dooralong', 'Double Bay', 'Douglas Park', 'Dover Heights', 'Doyalson', 'Doyalson North', 'Drummoyne', 'Duffys Forest', 'Dulwich Hill', 'Dundas', 'Dundas Valley', 'Dural', 'Durren Durren', 'Eagle Vale', 'Earlwood', 'East Gosford', 'East Hills', 'East Killara', 'East Kurrajong', 'East Lindfield', 'East Ryde', 'Eastern Creek')

suburb2 <- c('Eastgardens', 'Eastlakes', 'Eastwood', 'Ebenezer', 'Edensor Park', 'Edgecliff', 'Edmondson Park', 'Elanora Heights', 'Elderslie', 'Elizabeth Bay', 'Elizabeth Hills', 'Ellis Lane', 'Elvina Bay', 'Emerton', 'Empire Bay', 'Emu Heights', 'Emu Plains', 'Enfield', 'Engadine', 'Englorie Park', 'Enmore', 'Epping', 'Erina', 'Erina Heights', 'Ermington', 'Erskine Park', 'Erskineville', 'Eschol Park', 'Ettalong', 'Ettalong Beach', 'Eveleigh', 'Fairfield', 'Fairfield East', 'Fairfield Heights', 'Fairfield West', 'Fairlight', 'Faulconbridge', 'Five Dock', 'Flowerdale', 'Forest Glen', 'Forest Lodge', 'Forestville', 'Forresters Beach', 'Fountaindale', 'Freemans Reach', 'Frenchs Forest', 'Freshwater', 'Galston', 'Georges Hall', 'Gilead', 'Girraween', 'Gladesville', 'Glebe', 'Gledswood Hills', 'Glen Alpine', 'Glenbrook', 'Glendenning', 'Glenfield', 'Glenhaven', 'Glenmore', 'Glenmore Park', 'Glenning Valley', 'Glenorie', 'Glenwood', 'Glossodia', 'Gordon', 'Gore Hill', 'Gorokan', 'Gosford', 'Granville', 'Grasmere', 'Grays Point', 'Great Mackerel Beach', 'Green Point', 'Green Valley', 'Greenacre', 'Greendale', 'Greenfield Park', 'Greenhills Beach', 'Greenwich', 'Gregory Hills', 'Greystanes', 'Grose Vale', 'Grose Wold', 'Guildford', 'Guildford West', 'Gunderman', 'Gwandalan', 'Gymea', 'Gymea Bay', 'Haberfield', 'Halekulani', 'Halloran', 'Hamlyn Terrace', 'Hammondville', 'Harbord', 'Hardys Bay', 'Harrington Park', 'Harris Park', 'Hassall Grove', 'Hawkesbury Heights', 'Haymarket', 'Hazelbrook', 'Heathcote', 'Hebersham', 'Heckenberg', 'Henley', 'Hillsdale', 'Hinchinbrook', 'Hobartville', 'Holgate', 'Holroyd', 'Holsworthy', 'Homebush', 'Homebush Bay', 'Homebush West', 'Horningsea Park', 'Hornsby', 'Hornsby Heights', 'Horsfield Bay', 'Horsley Park', 'Hoxton Park', 'Hunters Hill', 'Huntington Heights', 'Huntingwood', 'Huntleys Cove', 'Huntleys Point', 'Hurlstone Park', 'Hurstville', 'Hurstville Grove', 'Illawong', 'Ingleburn', 'Ingleside', 'Jamisontown', 'Jannali', 'Jilliby', 'Jordan Springs', 'Kangaroo Point', 'Kangy Angy', 'Kanwal', 'Kareela', 'Kariong', 'Katoomba', 'Kearns', 'Kellyville', 'Kellyville Ridge', 'Kemps Creek', 'Kensington', 'Kenthurst', 'Kentlyn', 'Killara', 'Killarney Heights', 'Killarney Vale', 'Killcare', 'Killcare Heights', 'Kincumber', 'Kincumber South', 'Kingfisher Shores', 'Kings Cross', 'Kings Langley', 'Kings Park', 'Kingsford', 'Kingsgrove', 'Kingswood', 'Kirkham', 'Kirrawee', 'Kirribilli', 'Kogarah', 'Kogarah Bay', 'Koolewong', 'Kulnura', 'Kurmond', 'Kurnell', 'Kurraba Point', 'Kurrajong', 'Kurrajong Heights', 'Kurrajong Hills', 'Kyeemagh', 'Kyle Bay', 'La Perouse', 'Lake Haven', 'Lake Munmorah', 'Lakemba', 'Lakesland', 'Lalor Park', 'Lane Cove', 'Lane Cove North', 'Lane Cove West', 'Lansdowne', 'Lansvale', 'Lapstone', 'Laughtondale', 'Lavender Bay', 'Lawson', 'Leets Vale', 'Leichhardt', 'Lemon Tree', 'Leonay', 'Leppington', 'Lethbridge Park', 'Leumeah', 'Leura', 'Lewisham', 'Liberty Grove', 'Lidcombe', 'Lilli Pilli', 'Lilyfield', 'Linden', 'Lindfield', 'Linley Point', 'Lisarow', 'Little Bay', 'Little Jilliby', 'Little Wobby', 'Liverpool', 'Liverpool Westfield', 'Llandilo', 'Loftus', 'Londonderry', 'Long Jetty', 'Long Point', 'Longueville', 'Lovett Bay', 'Lower Macdonald', 'Lower Portland', 'Luddenham', 'Lugarno', 'Lurnea', 'Macmasters Beach', 'Macquarie Fields', 'Macquarie Links', 'Macquarie Park', 'Magenta', 'Maianbar', 'Malabar', 'Maldon', 'Mangrove Creek', 'Mangrove Mountain', 'Manly', 'Manly Vale', 'Mannering Park', 'Maraylya', 'Marayong', 'Mardi', 'Maroota', 'Maroubra', 'Maroubra Junction', 'Marrickville', 'Marsden Park', 'Marsfield', 'Mascot', 'Matcham', 'Matraville', 'Mays Hill', 'McGraths Hill', 'McMahons Point', 'Meadowbank', 'Medlow Bath', 'Megalong', 'Melrose Park', 'Menai', 'Menangle', 'Menangle Park', 'Merrylands', "Merrylands West")

suburb3 <- c('Middle Cove', 'Middle Dural', 'Middleton Grange', 'Miller', 'Millers Point', 'Milperra', 'Milsons Passage', 'Milsons Point', 'Minchinbury', 'Minto', 'Minto Heights', 'Miranda', 'Mona Vale', 'Monterey', 'Mooney Mooney', 'Mooney Mooney Creek', 'Moore Park', 'Moorebank', 'Mortdale', 'Mortlake', 'Mosman', 'Mount Annan', 'Mount Colah', 'Mount Druitt', 'Mount Hunter', 'Mount Kuring-gai', 'Mount Lewis', 'Mount Pritchard', 'Mount Riverview', 'Mount Vernon', 'Mount Victoria', 'Mount Wilson', 'Mowbray Park', 'Mulgoa', 'Mulgrave', 'Narara', 'Narellan', 'Narellan Vale', 'Naremburn', 'Narrabeen', 'Narraweena', 'Narwee', 'National Park', 'Nattai', 'Nelson', 'Neutral Bay', 'Newington', 'Newport', 'Newport Beach', 'Newtown', 'Niagara Park', 'Norah Head', 'Noraville', 'Normanhurst', 'North Avoca', 'North Balgowlah', 'North Bondi', 'North Curl Curl', 'North Epping', 'North Gosford', 'North Kellyville', 'North Manly', 'North Narrabeen', 'North Parramatta', 'North Richmond', 'North Rocks', 'North Ryde', 'North St Marys', 'North Strathfield', 'North Sydney', 'North Turramurra', 'North Wahroonga', 'North Willoughby', 'Northbridge', 'Northmead', 'Northwood', 'Norwest', 'Oakdale', 'Oakhurst', 'Oakville', 'Oatlands', 'Oatley', 'Old Guildford', 'Old Toongabbie', 'Oran Park', 'Orangeville', 'Orchard Hills', 'Ourimbah', 'Oxley Park', 'Oyster Bay', 'Pacific Palms', 'Paddington', 'Padstow', 'Padstow Heights', 'Pagewood', 'Palm Beach', 'Palm Grove', 'Panania', 'Parklea', 'Parramatta', 'Patonga', 'Peakhurst', 'Peakhurst Heights', 'Pearl Beach', 'Peats Ridge', 'Pemulwuy', 'Pendle Hill', 'Pennant Hills', 'Penrith', 'Penrith Plaza', 'Penshurst', 'Petersham', 'Pheasants Nest', 'Phegans Bay', 'Phillip Bay', 'Picketts Valley', 'Picnic Point', 'Picton', 'Pitt Town', 'Pleasure Point', 'Plumpton', 'Point Clare', 'Point Frederick', 'Point Piper', 'Port Hacking', 'Potts Hill', 'Potts Point', 'Prairiewood', 'Prestons', 'Pretty Beach', 'Prospect','Punchbowl', 'Putney', 'Pymble', 'Pyrmont', 'Quakers Hill', 'Queens Park', 'Queenscliff', 'Raby', 'Ramsgate', 'Ramsgate Beach', 'Randwick', 'Ravensdale', 'Razorback', 'Redfern', 'Regents Park', 'Regentville', 'Revesby', 'Revesby Heights', 'Rhodes', 'Richmond', 'Richmond Lowlands', 'Riverstone', 'Riverview', 'Riverwood', 'Rockdale', 'Rocky Point', 'Rodd Point', 'Rooty Hill', 'Ropes Crossing', 'Rose Bay', 'Rosebery', 'Rosehill', 'Roselands', 'Rosemeadow', 'Roseville', 'Roseville Chase', 'Rossmore', 'Round Corner', 'Rouse Hill', 'Royal National Park', 'Rozelle', 'Ruse', 'Rushcutters Bay', 'Russell Lea', 'Rydalmere', 'Ryde', 'Sackville', 'Sackville North', 'Sadleir', 'San Remo', 'Sandringham', 'Sandy Point', 'Sans Souci', 'Saratoga', 'Schofields', 'Scotland Island', 'Seaforth', 'Sefton', 'Seven Hills', 'Shalvey', 'Shanes Park', 'Shelly Beach', 'Silverdale', 'Silverwater', 'Smeaton Grange', 'Smithfield', 'Somersby', 'South Coogee', 'South Granville')

suburb4 <- c('South Hurstville', 'South Maroota', 'South Penrith', 'South Turramurra', 'South Wentworthville', 'South Windsor', 'Spencer', 'Spring Farm', 'Springfield', 'Springwood', 'St Albans', 'St Andrews', 'St Clair', 'St Helens Park', 'St Huberts Island', 'St Ives', 'St Ives Chase', 'St Johns Park', 'St Leonards', 'St Marys', 'St Peters', 'Stanhope Gardens', 'Stanmore', 'Strathfield', 'Strathfield South', 'Summer Hill', 'Summerland Point', 'Surry Hills', 'Sutherland', 'Sydenham', 'Sydney (CBD)', 'Sydney Olympic Park', 'Sylvania', 'Sylvania Waters', 'Tacoma', 'Tacoma South', 'Tahmoor', 'Tamarama', 'Taren Point', 'Tascott', 'Telopea', 'Tempe', 'Tennyson', 'Tennyson Point', 'Terrey Hills', 'Terrigal', 'The Entrance', 'The Entrance North', 'The Oaks', 'The Ponds', 'The Rocks', 'The Slopes', 'Theresa Park', 'Thirlmere', 'Thornleigh', 'Toongabbie', 'Toowoon Bay', 'Toukely', 'Toukley', 'Towlers Bay', 'Tregear', 'Tuggerah', 'Tuggerawong', 'Tumbi Umbi', 'Turramurra', 'Turrella', 'Ultimo', 'Umina', 'Umina Beach', 'Upper Colo', 'Valley Heights', 'Varroville', 'Vaucluse', 'Villawood', 'Vineyard', 'Voyager Point', 'Wadalba', 'Wagstaffe', 'Wahroonga', 'Waitara', 'Wakeley', 'Wallacia', 'Wallarah', 'Wamberal', 'Wareemba', 'Warnervale', 'Warragamba', 'Warrawee', 'Warriewood', 'Warrimoo', 'Warwick Farm', 'Watanobbi', 'Waterfall', 'Waterloo', 'Watsons Bay', 'Wattle Grove', 'Waverley', 'Waverton', 'Webbs Creek', 'Wedderburn', 'Wendoree Park', 'Wentworth Falls', 'Wentworth Point', 'Wentworthville', 'Werombi', 'Werrington', 'Werrington County', 'Werrington Downs', 'West Gosford', 'West Hoxton', 'West Pennant Hills', 'West Pymble', 'West Ryde', 'Westleigh', 'Westmead', 'Wetherill Park', 'Whalan', 'Whale Beach', 'Wheeler Heights', 'Wilberforce', 'Wiley Park', 'Willmot', 'Willoughby', 'Willoughby East', 'Wilton', 'Windsor', 'Windsor Downs', 'Winmalee', 'Winston Hills', 'Wisemans Ferry', 'Wolli Creek', 'Wollstonecraft', 'Woodbine', 'Woodcroft', 'Woodford', 'Woodpark', 'Woollahra', 'Woolloomooloo', 'Woolooware', 'Woolwich', 'Woongarrah', 'Woronora', 'Woronora Heights', 'Woy Woy', 'Woy Woy Bay', 'Wyoming', 'Wyong', 'Wyong Creek', 'Wyongah', 'Yagoona', 'Yanderra', 'Yarramalong', 'Yarramundi', 'Yarrawarrah', 'Yattalunga', 'Yellow Rock', 'Yennora', 'Yowie Bay', 'Zetland')

suburbs <- cbind(suburb1,suburb2, suburb3, suburb4)
```
```{r}
key <- "AIzaSyAZV49JhrDtgmPIWhw0pUvlVKBJ9Gr_k6I"
sub <- suburbs
```

# accounting firms
```{r}
queries <- paste0("Accounting firms in ", sub, ", NSW")

accounting_loop <- function(query, key, ntimes = 3, page_token = "") {
 print(query)    
 iter <- 0
 obj_df <- tibble()
 
  while(iter < ntimes & !is.null(page_token)) {
    iter <- iter + 1
    print(iter)
    obj_response <- google_places(search_string = query, key = key, page_token = page_token)
    obj_df_new <-   as_tibble(obj_response$results) %>% mutate(iter = iter)
    obj_df <- bind_rows(obj_df, obj_df_new)
    page_token <- obj_response$next_page_token
    
    if(is.null(page_token) == TRUE) {
      print("No more pagination tokens")
      Sys.sleep(2)
    } else {
    Sys.sleep(3) 
    }

  }
  
  obj_df
  
}

# Finally, we loop through the queries by the custom function.
df_blutspende <- map_df(.x = queries, .f = accounting_loop, key = key)
accounting_sydney <- df_blutspende

accounting_sydney$geometry$location
```

# Airport
```{r}
queries <- paste0("Airport in ", sub, ", NSW")

airport_loop <- function(query, key, ntimes = 3, page_token = "") {
 print(query)    
 iter <- 0
 obj_df <- tibble()
 
  while(iter < ntimes & !is.null(page_token)) {
    iter <- iter + 1
    print(iter)
    obj_response <- google_places(search_string = query, key = key, page_token = page_token)
    obj_df_new <-   as_tibble(obj_response$results) %>% mutate(iter = iter)
    obj_df <- bind_rows(obj_df, obj_df_new)
    page_token <- obj_response$next_page_token
    
    if(is.null(page_token) == TRUE) {
      print("No more pagination tokens")
      Sys.sleep(2)
    } else {
    Sys.sleep(3) 
    }

  }
  
  obj_df
  
}

# Finally, we loop through the queries by the custom function.
airport_sydney <- map_df(.x = queries, .f = airport_loop, key = key)
```

# Amusement Park
```{r}
queries <- paste0("Amusement parks in ", sub, ", NSW")

amusementpark_loop <- function(query, key, ntimes = 3, page_token = "") {
 print(query)    
 iter <- 0
 obj_df <- tibble()
 
  while(iter < ntimes & !is.null(page_token)) {
    iter <- iter + 1
    print(iter)
    obj_response <- google_places(search_string = query, key = key, page_token = page_token)
    obj_df_new <-   as_tibble(obj_response$results) %>% mutate(iter = iter)
    obj_df <- bind_rows(obj_df, obj_df_new)
    page_token <- obj_response$next_page_token
    
    if(is.null(page_token) == TRUE) {
      print("No more pagination tokens")
      Sys.sleep(2)
    } else {
    Sys.sleep(3) 
    }

  }
  
  obj_df
  
}

# Finally, we loop through the queries by the custom function.
amusementpark <- map_df(.x = queries, .f = amusementpark_loop, key = key)
```

